### ISSUE TITLE
Digit pattern ### does not work with bash glob like * or ?

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#100]
When importing from a directory (/home/igbmc/gsharov/test/scipion/relion13_tutorial/betagal/PrecalculatedResults/Class3D) and specifying the pattern, e.g. *class###.mrc I get an error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/igbmc/gsharov/soft/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __ call __
    return self.func(*args)
  File "/home/igbmc/gsharov/soft/scipion/pyworkflow/gui/form.py", line 1511, in execute
    errors = self.protocol.validate()
  File "/home/igbmc/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 1228, in validate
    childErrors = self._validate()
  File "/home/igbmc/gsharov/soft/scipion/pyworkflow/em/protocol/protocol_import/base.py", line 119, in _validate
    for imgFn, _ in self.iterFiles():
  File "/home/igbmc/gsharov/soft/scipion/pyworkflow/em/protocol/protocol_import/base.py", line 197, in iterFiles
    raise Exception("File '%s' doesn't match the pattern '%s'" % (fileName, self.getPattern()))
Exception:

**File '/home/igbmc/gsharov/test/scipion/relion13_tutorial/betagal/PrecalculatedResults/Class3D/run1_it000_class001.mrc' doesn't match the pattern '/home/igbmc/gsharov/test/scipion/relion13_tutorial/betagal/PrecalculatedResults/Class3D/*class[0-9][0-9][0-9].mrc'**

**Comment by delarosatrevin** [comment]
I was looking at this issue and the problem arises from the combination of bash patterns and the special ### notation. For the moment it can only be used one or the other, but not both together. We need to check this in deep.

Anyway, in your example the use of ### was not right, since it is for mark some digits as IDs that should be unique. In your case, the 3 digits are not unique since you have the same class numbers for different iterations. Here the import can work with the following pattern:  *class???.mrc  and the ids will be automatically set from 1 to N.

Thanks for the feedback.

**Comment by pconesa** [comment]
Hi guys! @azazellochg and @delarosatrevin , I guess this issue can be closed? or do you see the need of having a "digit" wildcard not being used later as an id.

**Comment by azazellochg** [comment]
@pconesa I guess you can close it, combination of * and ? seems to be enough
