### ISSUE TITLE
Style of the "Export references"

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1004]
@pconesa and @yaizar I would like to discuss about the current "look" (and feel) of the "Export references" button. I think that it break with the layout of this tab. First, it is in red (the "hot" style), bringing it to the same importance level than "Analyze Results" and I think that it is not. Secondly, it just sticks a new button at the end of this tab which, at least for me, does not look very well. The name does not correspond very well with the action, since one would expect that "export" let you choose where (as the folder icon suggest) and the output format. 

My proposition to discuss:
* Remove the red button and put as a link (similar to the one of each reference) just after the word: REFERENCES. Maybe something like REFERENCES (Open as bibtex). I think that the user should know what bibtex is, if not, this function is useless anyway.

**Comment by pconesa** [comment]
Thanks Jose,

We first tried your suggestion, to avoid the button. But we couldn't 
find a way to do it. Secondly, we decided to go for the button, and 
Yaiza showed up the file browser t allow the user to choose where to 
save it. After a while people suggested to show the file with the text 
instead of the file browser.

There is a problem with the current implementation where the file 
extension (.bib) is not associated with any program it may freeze 
because it is trying to open some kind of console editor (emacs or vim, 
not sure).

Regarding the style.....I like the fact that it is present red and quite 
visible.....I think it make clear how to export the references and 
therefore making easy the citations of all the packages used. I agree 
that it creates a new line and it does not look right.

My proposition to discuss (;-):

Leave it as a button, "degrade" it to grey, may be and may be change the 
extension to txt just to aviod the freezing case (not sure how often 
will this happens but better to prevent it).

**Comment by delarosatrevin** [comment]
Pablo, I agree that the Button make it quite visible, but I disagree that it should be in that way. My guess is that this function will not be used so frequently, so there is not need to make it so visible (and breaking our general aesthetics ). Imagine that this will be mainly used for publication, so after all processing (or most of it) have been done. Then, we need to remove the people that use their own reference manager or that use other than bibtex. Not many left, I would say. 

Anyway, I have created a branch named 'references-link' and I made it as a link (as shown in the image below). Do you think that way is visible and clear? For me it keeps the same style as the reference links and everything around in the tab. I left commented a line where the bibtex file can be opened with our home-made text file viewer. This will not freeze, but right now I don't like the black background (can be changed if propagating the options) and the lines numbering of our file text viewer. 

![image](https://cloud.githubusercontent.com/assets/8441688/26093992/64f4b10a-3a18-11e7-8ea2-3bd2c4ad2964.png)

**Comment by yaizar** [comment]
This looks good! I don't see the changes in the branch though, let me know when you push them @delarosatrevin

**Comment by delarosatrevin** [comment]
Hum...it seems that I accidentally committed the change to release-1.1-fixes branch, it is commit b95bd00679ef90f08185b14eed68ed11c15b5440

**Comment by pconesa** [comment]
Looks like what we wanted initially to do. Thanks, we'll have a look and 
we'll do it this way I agree, though  I liked the idea "overstating" 
that there is a "button to export the citations".

I see you have already pushed "accidentally" to fixes....is that the way 
to collaborate from now on? ;-)....he,he...no problem we will look to 
see if , leaving it there we can highlight it a bit more (bold font...)

We were using our "home-made" way to open the file, so I guess the 
freeze problem is still there. It happened in a server, and we fixed it 
associating the .bib mime type to a program something like:

https://unix.stackexchange.com/questions/251054/how-does-the-xdg-open-command-know-which-application-to-use-to-open-a-file

Yaiza will write a troubleshooting line for this case.
