### ISSUE TITLE
Scipion fails when the filemane has " - "

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1073]
It is interpreted a a parameter in xmipp programs and may be others

Possible solutions:

escape special characters
pass file names as between ""
...

**Comment by yaizar** [comment]
Which filename?

**Comment by yaizar** [comment]
OK I missed the space around the -, got it

**Comment by yaizar** [comment]
@cossorzano can you give me more details on this? I'm not able to reproduce:
![image](https://user-images.githubusercontent.com/4609687/28163254-a94d2244-67ca-11e7-8099-42c253e9b1af.png)

![image](https://user-images.githubusercontent.com/4609687/28163325-fc90541c-67ca-11e7-8021-967a5896b07e.png)

**Comment by pconesa** [comment]
@yaizar , this fails when using the file un an xmipp protocol...try a movie alignment after import.

**Comment by cossorzano** [comment]
It fails when after importing you try to do correlation alignment

**Comment by yaizar** [comment]
So I've fixed it for both correlation and optical alignment, BUT! If we wanna use xmipp picking next, the picker doesn't launch. I get a window saying:
`SEVERE: No enum constant xmipp.viewer.particlepicker.training.model.Mode.`
and a veeeery long list of warnings and errors that prevent the picker from opening (see picture below).  At this point it's hard to continue fixing paths in commands, because we use the `micrographs.sqlite` to launch the picker with this command: 
```
java -Xmx2g -d64 -Djava.library.path=/home/yaiza/scipion/scipion/software/em/xmipp/lib -Dplugins.dir=/home/yaiza/scipion/scipion/software/em/xmipp/external/imagej/plugins -cp /usr/lib/jvm/java-8-openjdk-amd64/lib/*:/home/yaiza/scipion/scipion/software/em/xmipp/external/imagej/*:/home/yaiza/scipion/scipion/software/em/xmipp/java/lib/* xmipp.viewer.particlepicker.training.SupervisedPickerRunner --input "Runs/000381_XmippProtOFAlignment/micrographs.sqlite" --output "Runs/000449_XmippProtParticlePicking/extra" --scipion 59375
``` 
Whatever follows is xmipp's dark magic failing to read filenames with spaces. Errors will likely happen with a good bunch of protocols that need those filenames as arguments for their command line calls (hard to find how many of them, probably mostly xmipp but others potentially too).

So! I think it is in everyone's interest to avoid filenames with spaces :) If the space is in the folder we aren't even able to import anything as of now. Anyone against having a space-in-filename validation and warning at the very beginning?

![image](https://user-images.githubusercontent.com/4609687/28424677-795691ca-6d6e-11e7-9ebc-b31f64b1a2be.png)

**Comment by yaizar** [comment]
I'm gonna follow @josuegbl 's advice and remove the spaces when we create the file copies/symlinks at the very beginning (I wasn't aware of those! minimum amount of code & fixes most problems :) ). I'll look a bit into the white spaces in the folder name, but I think this is a different issue that's most likely gonna remain for now.
