### ISSUE TITLE
opening a list of input particles is very slow in a large project

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1089]
I have a fairly large project and every time I open a list of input particles, it takes over one minute to open - can it be made quicker?

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, we has found the same issue and it seems to be related to having some 2D classification runs with large number of classes. It looks like the tree needs to be populated with many items. We have fix (workaround) and it is almost instantaneous now, we just avoid adding classes as sub-items. What Scipion version are you using? We are preparing a release with facilities features soon, but if you don't want to take the risk I can help you to apply the patch for that.

**Comment by JuhaHuiskonen** [comment]
Hi @delarosatrevin please email me a patch. I am running 1.1

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen , I have created a branch in the OPIC fork of Scipion. The branch is named 'release-1.1.1-opic' and it is based on v1.1 with some minor bugfixes. I have also added the fix for avoiding the slow selection of inputs. If you do not have OPIC as a remote, you should add it with the following command.

```
git remote add opic https://github.com/OPIC-Oxford/scipion.git
```
Then you only need to switch for that branch as:
```
git checkout -b release-1.1.1-opic -t opic/release-1.1.1-opic
```

Please let me know if that worked for you. This branch should contain a bugfix made by @pconesa about the refresh status of the protocols. If still does not work in your cluster, we can force it to always refresh.

**Comment by delarosatrevin** [comment]
Hi @JuhaHuiskonen, has you have time to try this fix?

**Comment by JuhaHuiskonen** [comment]
Hi @delarosatrevin I tried and this happens:

git checkout -b release-1.1.1-opic -t opic/release-1.1.1-opic

fatal: git checkout: updating paths is incompatible with switching branches.
Did you intend to checkout 'opic/release-1.1.1-opic' which can not be resolved as commit?

**Comment by delarosatrevin** [comment]
Maybe the command does not work for that particular git version. Just try:

git checkout release-1.1.1-opic 

Let me know if that works. I have updated that branch right now...so it is based on release-1.1.1 plus the fix for quicker selection of input objects.

**Comment by JuhaHuiskonen** [comment]
OK, that git command worked but It still takes about 3 min to open the list of particles sets

**Comment by pconesa** [comment]
@delarosatrevin , can I close this?

**Comment by delarosatrevin** [comment]
Yes, I think this is fixed already.
