### ISSUE TITLE
Gautomatch wizard improvements

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1124]
Suggested by K.Zhang:
The wizard do not need to start the program every time the user changes Threshold - we could simply filter the picking results (we have all the peaks sorted by CC). However if inter-particle distance is changed, the program has to be re-run.

**Comment by delarosatrevin** [comment]
Thanks for the feedback. I got a couple suggestions related to this over here.

* In Relion auto-pick wizard, would be better to re-launch the programs for the subset of micrographs (rather than one by one). Will this way be better for Gautomatch as well?
* Highlight (or show the numbers) of new particles (removed particles) after changes in the parameters in the wizard (to have an idea how the changes are affecting the number of particles).

Apart from that, in Relion protocol I have implemented a quick way to pick up a subset of micrographs that covers all the defocus range to optimize the parameters for those first. Would something like this be helpful for Gautomatch as well?

**Comment by azazellochg** [comment]
I think creating a defocus range subset would be very useful. I always have to do to it manually sorting the mics table. Not sure about number of new particles though - I think this is obvious from total count in the table.
PS. Other things we were discussing long time ago - color particles by CC values and add defocus column to Xmipp picker table, there might be already issues created for this, I don't remember.

**Comment by azazellochg** [comment]
moved to https://github.com/scipion-em/scipion-em-gautomatch/issues/5
