### ISSUE TITLE
alignment errors 

### ISSUE THREAD

**Issue by pascalalbanese** [I2PC/scipion#1127]
scipion v1.0.1

the alignment of my particles abort with any protocol, both on the uncropped or the cropped ones. The message is the following:

Protocol failed: Command 'mpirun -np 2 -bynode  `which xmipp_mpi_classify_CL2D` -i Runs/000939_XmippProtCL2DAlign/extra/images.xmd --odir Runs/000939_XmippProtCL2DAlign/extra --nref 1 --iter 10 --maxShift 10 --nref0 1' returned non-zero exit status 127

with spider is:

Protocol failed: Ouptput stack Runs/000971_SpiderProtAlignAPSR/apsr/stkaligned.stk not produced.

if you can help me somehow it would be great.

Pascal

**Comment by azazellochg** [comment]
@pascalalbanese Dear Pascal, thanks for reporting this. Could you please attach log files for both protocols (Runs/000971_SpiderProtAlignAPSR/logs/run.stdout and Runs/000939_XmippProtCL2DAlign/logs/run.stdout)?

**Comment by pascalalbanese** [comment]
[log file scipionsupport.tar.gz](https://github.com/I2PC/scipion/files/1152598/log.file.scipionsupport.tar.gz)

**Comment by pascalalbanese** [comment]
the (copy) is the xmipp one

**Comment by pascalalbanese** [comment]
another quick question, how can i open an existing project on external HD od another partition?

**Comment by azazellochg** [comment]
@pascalalbanese thanks

1. Spider gives an error because it requires csh installed.
2. Xmipp gives an error because openmpi was not properly setup/linked in scipion. I suggest to check MPI-related vars in scipion config file and make sure you can launch a simple test (e.g. `scipion run mpirun -np 4 hostname`)

If I correctly understood your last question, you can create a symbolic link in ScipionUserData/projects folder pointing to your project mounted elsewhere.
