### ISSUE TITLE
RLN_MICROGRAPH_NAME is always set to MicId

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1145]
This thing looks almost as old as Scipion :) I just wanted to know why this is so? Was this some old bugfix? 
If the particles do not have associated micrographs then it would make sense to set this to micId, but otherwise micName should be preserved (since its rendered by default when displaying particles, I see nice red crosses... 

https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/relion/convert.py#L382

**Comment by delarosatrevin** [comment]
Yes, maybe it is a good moment to review this. I think the original reason was because in early versions of Relion, it used that field to group the particles by CTF....which probably is no longer the case. Nevertheless, the micName is kind of id, so it is possible that it does not exist. In fact, if you start by importing movies...the micName will be generated based on the movie name and propagated to micrographs.
