### ISSUE TITLE
protocol to expand symmetry

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#1165]
Hi @josuegbl @delarosatrevin  Could you please add a protocol for 'relion_particle_symmetry_expand' please. This would be beneficial in focused 3D classification and localized reconstruction workflows.  Also, I think you could do the same easily by modifying the existing protocol 'xmipp3 - break symmetry'.. Instead of writing one of the many symmetry related orientations, you would simply write all of them (each still referring to the original particle). Name suggestion for this would be 'xmipp3 - expand symmetry'. Many thanks.

**Comment by delarosatrevin** [comment]
Thanks a lot @JuhaHuiskonen for your feedback. I will discuss with @josuegbl and try to implement it as quick as possible.

**Comment by JuhaHuiskonen** [comment]
Hi @delarosatrevin any update on this?

**Comment by azazellochg** [comment]
Hi @JuhaHuiskonen @delarosatrevin 
I have added relion expand protocol to az-relion2.1 branch, you can have a look and test.

**Comment by delarosatrevin** [comment]
@azazellochg Thank you so much for this! I haven't had time to look at it. @josuegbl and myself are looking in the Relion 2.1 PR to merge this into release-1.1.1 branch.

Since we are planning an upcoming release with some facility-oriented features (not exclusively, such as: picking in streaming and extraction). We are planning to merge both release-1.1.1 and release-1.1-facilities-devel and it will be the next release (either v1.1.1 or v1.2).

So, @JuhaHuiskonen you will have this probably next week, but in a relatively stable development branch, where errors can arise.
