### ISSUE TITLE
localizedRec uses wrong relion version

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1355]
To reproduce:
1) set in config RELION_HOME = %(EM_ROOT)s/relion-2.1 and LOCALREC_RELION_HOME = %(EM_ROOT)s/relion-1.4
2) the protocol will try to use relion2 instead of 1.4

If both vars are set to 1.4 then it's ok.
PS. I checked the os.environ and it has 1.4 set, not 2.0 (except RELION_HOME var which is 2.0). Localrec uses os.system(command), but I don't know where it gets 2.0 version from, I dont have anything in bashrc..

**Comment by pconesa** [comment]
@azazellochg thanks, we'll have a look.

**Comment by pconesa** [comment]
Hi @azazellochg , I got a similar scenario and, at least the test works fine. Actually, I've moved %(EM_ROOT)s/relion-2.0 out of software/em  to be sure that is finding it.

scipion test tests.em.protocols.test_protocol_localized_reconstruction.TestLocalizedRecons

Actually, the tesst fails in the last stpe which is using relion 2.0 to reconstruct and, because I've moved it away it does not validate.

**Comment by azazellochg** [comment]
Hi @pconesa , I am not sure I follow, what did you do with relion-2.0? In my case the test protocol cannot start because it is using wrong relion.

**Comment by pconesa** [comment]
Yes, in my case it failed because I intentionally corrupted Relion installation moving it out of the path (this was just to check that localrec protocols uses relion 1.4.

In my case, these settings worked and passed the test completely:
RELION_HOME = %(EM_ROOT)s/relion-2.0
LOCALREC_RELION_HOME = %(EM_ROOT)s/relion-1.4

Not sure if having 2.1 (this is the beta and was removed some time ago) makes a difference.

**Comment by azazellochg** [comment]
You are right, if I put non-existing path in RELION_HOME then it works.

**Comment by pconesa** [comment]
Just to clarify a bit more:
My test failed in the last protocol, which is a RELION reconstruct protocol, and this is due to my "intentionally" currupted of RELION installation.
![image](https://user-images.githubusercontent.com/785633/33321821-484c438c-d447-11e7-8bde-c5b067b22f58.png)

That way I can be sure that the 
![image](https://user-images.githubusercontent.com/785633/33321919-ab110188-d447-11e7-9bfc-0255ee89cb77.png)
relion_refine command is from 1.4 and no from my 2.0 installation.

Am I missing anything?

**Comment by pconesa** [comment]
So you probably have a  relion non working version? currently supported one should be 2.0, although can't see why the "ephimeral" 2.1 you might have should not work.

**Comment by azazellochg** [comment]
Ah, I see now. Relion-2.0 works (and localrec test still uses it besides specifying 1.4 in config). Relion-2.1 apparently has changes in default options:
```
00014:   The following errors were encountered upon command-line parsing: 
00015:   ERROR: Argument --i not found or invalid argument
00016:   ERROR: 
00017:   Errors encountered on the command line (see above), exiting...
00018:   File: /net/nfs1/public/EM/RELION/relion-2.1/src/ml_optimiser.cpp line: 1280
00019:   ** Running command: relion_refine --sym I3 --print_symmetry_ops --o ./ > relion_symops.tmp
```

**Comment by pconesa** [comment]
Gotcha!!! Good to know, something to have in mind when rescuing relion-2.1
@josuegbl , bear this in mind please.

**Comment by josuegbl** [comment]
Well, this issue is related to the way to run relion programs inside localrec code (matrix3.py). There, a runProgram function is imported from pyworkflow/em, and the relion enviroment is set from relion convert; using a relion version that could be incompatible with the command line that localrec wants to execute. In facilities-fixes is fixed editing RELION_HOME environ variable, but I think that we need to set the proper environment in runProgram function.

**Comment by pconesa** [comment]
@josuegbl this is not yet in facilities branch right?, you are already testing this?
The test is failing in buildbot.
