### ISSUE TITLE
HTML report: Show CTF data when no movies

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1366]
Extracted from #1333, from Gregory:
"the micrograph table is empty when I'm running protocols on the image attached above.. would be nice to see ctf results, even if no shift plots are available (we can show simply "No data" or simply hide the column when no movie alignment is running).

Also, autopicking protocol is missing from Name column (coordinates are not coming from ctffind :)
![screenshot_20171123_143148](https://user-images.githubusercontent.com/6952870/33177618-2f85cee4-d05b-11e7-8b44-c79eb0fbf23f.png)"

**Comment by yaizar** [comment]
Fixed issue 1 in  bf5c714.
As for the second one, I haven't been able to reproduce:
![image](https://user-images.githubusercontent.com/4609687/34383728-a16b5372-eb17-11e7-87fc-db04832995f4.png)

@azazellochg do you remember which picking were you using?

**Comment by azazellochg** [comment]
@yaizar thanks, the first problem solved! For the second one - you can run TestRelionExtractStreaming and if you create a summary protocol then in HTML report you will see coordinates coming from ctffind

**Comment by yaizar** [comment]
Thanks @azazellochg. I've now been able to reproduce with that test:
![image](https://user-images.githubusercontent.com/4609687/34440351-fb26f972-ecb4-11e7-9b5c-9ea8249f1796.png)
So I guess this problem was partially introduced by _me_ (oops) in bd7c610 ( in the [summary provider](https://github.com/I2PC/scipion/commit/bd7c610afe88bfa562d73ad72d9bdb474879584b#diff-974f2f13ecfc99fdf5ce7123e867993b), to be specific), but this commit apparently prevents having duplicate protocols in the runs table. However there is an underlying issue: the **outputCTF** has **objId=111**, which is the same as **StreamingAutoPicking**. It goes unnoticed but the console where scipion launches also shows an error message (when we click on the monitor summary's analyze results button):
![image](https://user-images.githubusercontent.com/4609687/34440651-d71236b2-ecb6-11e7-8f71-83c743688b8b.png)
So more than an html report issue this seems to be an issue with the way the object ids are assigned? Should an output object and a protocol object be allowed to have the same id? It has me a little bit puzzled that I've been able to reproduce this using the relion test too, it's not a problem that is reproduced easily!

**Comment by yaizar** [comment]
@josuegbl I think the test itself is causing the duplicate id because the outputCTF should have the id=111, but the auto-picking is launched before there's any output so it is assigned the id=111 too. Is there any reason why we do this [waitOutput ](https://github.com/I2PC/scipion/blob/release-1.1.facilities-fixes/pyworkflow/tests/em/workflows/test_workflow_streaming.py#L271) after the auto-picking instead of doing it earlier, immediately after launching the ctf?
