### ISSUE TITLE
low freq default value ctf viewer

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1369]
Somewhere around [here](https://github.com/I2PC/scipion/blob/release-1.1.facilities-devel/software/em/xmipp/java/src/xmipp/viewer/ctf/CTFRecalculateImageWindow.java#L126), in recalculate ctf viewer, low freq limit could be set by default to 0.05, because 0 value (now default) is not accepted.

**Comment by azazellochg** [comment]
Also, maybe the default values could be taken from the protocol where it was run? This would be very convenient so I don't have to change it for every psd

**Comment by dmaluenda** [comment]
Thanks Gregory,

Making the frequency interval passed in the protocol is a very good idea, however this is not easy with an elegant way. What a pity because it would be great. By the moment, we put the default value of all the CTF protocols (0.05).   

Committed in Facilities-fixes [5627fb947da04f1491663bd9f7cb0ec0167b4238]
