### ISSUE TITLE
failed movies added to output

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1394]
When motioncor fails (I checked only in streaming), the failed movies are still added to the dataset (they have no shifts). This should be avoided.
![screenshot_20171218_101230](https://user-images.githubusercontent.com/6952870/34101133-9951b8da-e3dc-11e7-9cb4-d77b5e2e9a3c.png)
![screenshot_20171218_101545](https://user-images.githubusercontent.com/6952870/34101141-a14fdb48-e3dc-11e7-87fb-becf6a7419ab.png)

PS. All the warnings are properly shown:
```
...
02682:   WARNING: Micrograph Runs/000465_ProtMotionCorr/extra/Grigori_1030_aligned_mic_DW.mrc was not generated, can't add it to output set.
02683:   WARNING: Micrograph Runs/000465_ProtMotionCorr/extra/Grigori_1031_aligned_mic_DW.mrc was not generated, can't add it to output set.
02684:   WARNING: Micrograph Runs/000465_ProtMotionCorr/extra/Grigori_1032_aligned_mic_DW.mrc was not generated, can't add it to output set.
02685:   WARNING: Micrograph Runs/000465_ProtMotionCorr/extra/Grigori_1033_aligned_mic_DW.mrc was not generated, can't add it to output set.
02686:   STARTED: createOutputStep, step 1026
02687:     2017-12-16 00:52:45.751895
02688:   WARNING - Failed to align 160 movies.
```

**Comment by pconesa** [comment]
thanks @azazellochg , will have a look.

**Comment by pconesa** [comment]
@azazellochg , I'm confused....is the output wrong for the motioncor protocol or is it for the summary monitor.

**Comment by azazellochg** [comment]
@pconesa both show wrong output. I guess motioncor is wrong.

**Comment by yaizar** [comment]
We're removing this from facilities as the set of micrographs is properly created (the warning refers to this one).  Motioncorr generates a set of movies even if we don't choose the "Save movies" option (shown in advanced mode). The set of movies generated in this case is just a copy of the input set and it is in no way connected to the success of alignment, is this the desired behavior? Should we generate a set of movies at all? Was this your case @azazellochg?
If we select "save movies" then the alignment and the new movie are connected, so the alignment protocol should check and warn about movies like it does with micrographs now.

**Comment by yaizar** [comment]
@azazellochg could you send me one of those failed movies? rancelyaiza@gmail.com

**Comment by azazellochg** [comment]
Hi @yaizar , just to clarify: by default (Save movie = false) the output movie is the same as input but has alignment information. If Save movie = True, then motioncor2 writes aligned movie stacks, so in Scipion the output movies are associated with these new files, but they have no alignment, since the frames are already aligned. The idea of not generating aligned movie stacks is to save disc space of course. 

Anyway, the output movies from motioncor2 are used in protocols further down in the pipeline (movie refinement or polishing), so they should not be produced at all if the alignment has failed.
I am travelling now but I will send you one of the failed movies later.

**Comment by yaizar** [comment]
Okay, so a little bit of external input is needed here @cossorzano @azazellochg @delarosatrevin @pconesa @josuegbl. The issue here is that if we have a failed alignment for a given movie, the movie is added to the output movie set (which is presumably wrong) and the micrograph is not added to the mic set, so we end up with discrepancies between output movie and output micrograph sets (see azazellochg's first post on this issue or my example below). What we do for the micrograph set is checking if the mic path exists. The case of the movies is a little more tricky, because a successful alignment doesn't necessarily mean a new movie file (we might just use the input movies and add the alignment attributes).  Now my question for you gentlemen is: is this discrepancy between movie set and mic set really **wrong**? If it is, how do we define if a movie has the right alignment before adding it to the output set, in a way that is generic for all alignment protocols? 

Here is an example of an output where the alignment of the single movie in the set wasn't successful (ignore the "No dim" in the movie set because that was just me triggering the unsuccessful alignment): 
![image](https://user-images.githubusercontent.com/4609687/35631492-548e94d0-06a4-11e8-91da-9acc51e33905.png)
And here are the values of said movie:
![image](https://user-images.githubusercontent.com/4609687/35631362-007f445c-06a4-11e8-8547-acab99f0d581.png)
The first thing that comes to my mind is to define successful movie alignment as a non empty _alignment.xshifts field. Thoughts? 

Thanks :-)

**Comment by azazellochg** [comment]
@yaizar I agree that empty _alignment.xshifts would indicate failed alignment

**Comment by azazellochg** [comment]
@pconesa I guess this can be closed? Just checked it  and it works.

**Comment by pconesa** [comment]
Is not this what was rolled back recently? @yaizar

**Comment by yaizar** [comment]
Rolled back and fixed again, it can be closed
