### ISSUE TITLE
isStreamClosed() is always true

### ISSUE THREAD

**Issue by majtner** [I2PC/scipion#1433]
While testing streaming on particles I noticed that method isStreamClosed() defined in object.py is always True, even if the parent protocol is still running.

**Comment by josuegbl** [comment]
this is because this method is used to close the sets.

**Comment by majtner** [comment]
I am not sure if understand correctly but on multiple places in code, there is condition like this:
self.finished = self.streamClosed and allDone == nMics
where self.streamClosed evaluates isStreamClosed() on items from parent protocol.

Therefore, the condition to finish my current protocol depends on condition streamClosed, which is, in my case, always true. 

I want to wait until there are new items coming (while previous protocol is running) and I always though this is the right condition for it. If isStreamClosed() is not testing it, how can I determine whether the stream is still running?

**Comment by josuegbl** [comment]
I think you are misunderstanding the condition here: self.finished = self.streamClosed check whether self.finished is true or not, whatever means self.finished in your case. Usually self.finished is true if the input(s) SetOfWhatever is(are) closed, which means that there are not new items coming.
I think the code is more easy to read if you write self.finished = self.streamClosed  instead of self.finished = True.
In any case, you can re-define isStreamClosed() method in your protocol, and use it accordingly.

**Comment by majtner** [comment]
Maybe I can a bit more specify that this problem appears when the class inherits from ProtProcessParticles, where input particles are defined in _defineParams and not in _defineProcessParams as all other params.
Probably it is not important here but this is the only difference I see in terms of defining the pointer to input.

**Comment by majtner** [comment]
Thanks to @pconesa the problem is solved.
The bug was in ProtCreateStreamData, where after the first iteration, StreamState was by mistake set to STREAM_CLOSED.
I have already fix it and I will add it to the next pull request.
