### ISSUE TITLE
CTFfind 4 uses slower more exhaustive search and we cannot change

### ISSUE THREAD

**Issue by andreanans** [I2PC/scipion#1458]
Hi,

I noticed that by default CTFFind 4 uses the slower for exhaustive search by default and we cannot change this in Scipion. Would it be possible to add the option to switch this to no?

Thank you

**Comment by delarosatrevin** [comment]
Hi @andreanans,

I noticed the same recently. It was changed accordingly to the default of ctffind4 (< 4.0 and >4.1.8). 
I just added an option to the protocol form, so it would be easy to switch the slow search on/off.

It should be add soon after the PR #1454 is approved and merged to the release candidate branch.
So, I will close this issue since it has been solved here d7a9a4c8687d24a5e4c7ee1c93f1ce99e343fa3e.

Thanks for let it us know.
