### ISSUE TITLE
Add consider proirs option to relion base protocol (from #1402)

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1463]
> So perhaps there should be two separate options:
> 
> consider previous alignment (not a default - if selected will copy the alignments but not the priors)
> consider alignment as priors (not a default and perhaps this should be an additional, advanced option evoked only if 1 is chosen - if selected will copy the alignments also as priors).

**Comment by josuegbl** [comment]
@azazellochg, in which situation you want to consider the  previous alignment but not the PRIORS?

**Comment by azazellochg** [comment]
@josuegbl,  when I want to do 3D classification using angles from 3D refinement without sticking to priors (so that angles can still drift away)

**Comment by josuegbl** [comment]
Ok, now I see the convenience to separate into two options. I do it now.

**Comment by azazellochg** [comment]
@josuegbl thanks. So setting priors should be removed from "Consider previous alignment=YES" option. It should be done only when (new) option "Set priors to input angles or similar)"=Yes

**Comment by azazellochg** [comment]
Just to clarify my point, I've just talked to Sjors about it. By default, in Relion when starting local searches (classification or refinement), the --sigma_ang option is used --> the local searches will be around the optimal angles (and translations) from the previous iteration, and will thus be able to slowly move away.
If someone wants to be stuck in local minima then and only then PRIORS should be set in a star file (manually, there is no option in relion for this)

**Comment by delarosatrevin** [comment]
Yes, I also talked to Sjors during the last EMBO course in London and I clarified myself a little bit...but still is a bit confusing in general. I think that in Relion, there is no way to specify a binary image + metadata, that is what the alignment means in our data model. It is just staying that you can represent an image with binary data (pixels values) and some transformation matrix. 

In Relion, this information is generated per iteration, but not used, unless the local search as PRIORS. I agree with @azazellochg that we should try to adhere to the philosophy of the package and treat the priors as a different thing. I will propose to make an expert/hidden/advanced option (since we are not in favor of manual editing for traceability and reproducibility) but not very visible by default.
