### ISSUE TITLE
screen particles - add features problem (devel branch)

### ISSUE THREAD

**Issue by majtner** [I2PC/scipion#1469]
In xmipp3 - screen particles, there seems to be two problems with adding features:
- A1D_ELEM(v0,0) is not added to features (to v04 vector) -> this can be easily fixed
- A1D_ELEM(v1,n) for n=0 seems to be always 2500.0, at least in all my tests on devel. I believe there might be a problem in derivation of this feature; code is in image_sort_by_statistics.cpp, line 238

**Comment by 1aviervargas** [comment]
Hi Thomas,

In devel branch v0 is included to v04 vector in line 218
(v04.push_back(A1D_ELEM(v0,index));)

Additionally, there is no any v1 element, the multidimarrays are v0, v1, v2
and v3. About the values I run a simple test: I run TestRelionRefine and I
run screen particles. I got the following values for :

        std::cout << "  " << A1D_ELEM(v0,0) << "  " << A1D_ELEM(v2,0) << "
" << A1D_ELEM(v3,0) << "  " << A1D_ELEM(v4,0) << std::endl;

00015:      0/   0 sec.   157.394  0.470648  16607.3  -1.05573
00016:      0/   0 sec. .  105.808  0.473396  14952.9  -1.13602
00017:      0/   0 sec. ..  156.765  0.471671  16587.3  -1.05271
00018:      0/   0 sec. ...  163.282  0.472263  17342.8  -1.04064
00019:      0/   0 sec. ...  140.685  0.436708  15884.5  -1.07583
00020:      0/   0 sec. ....  150.89  0.472728  16591.6  -1.15753
00021:      0/   0 sec. .....  166.079  0.45212  17373.8  -1.02319
00022:      0/   0 sec. ......  117.173  0.446506  15955.1  -1.08197
00023:      0/   0 sec. .......  151.844  0.464068  16321.5  -1.04905
00024:      0/   0 sec. .......  121.764  0.465757  16327.4  -1.07105

Best
Javier

**Comment by majtner** [comment]
Hi Javier,

> In devel branch v0 is included to v04 vector in line 218 (v04.push_back(A1D_ELEM(v0,index));) 
The problem is that index starts from 1 and element A1D_ELEM(v0,0) = (tempM*ROI).sum(); is never added to v04 vector.

> Additionally, there is no any v1 element, the multidimarrays are v0, v1, v2 and v3.
v1 is defined later in the code, not in the beginning with other vectors. There is a comment about it:
//The size of v1 depends on the image size and must be declared here
There is line 238, where v04.push_back(A1D_ELEM(v1,n)); in for loop, which goes from n = 0 and I believe that this first value is problematic. The other values, including those you printed, are all ok.

**Comment by 1aviervargas** [comment]
Hi Tomas,

The problem is that index starts from 1 and element A1D_ELEM(v0,0) =
(tempM*ROI).sum(); is never added to v04 vector.

Ok, now I see.. you are right. I do not have the code fresh but I think
that should be a reason for excluding 0... not sure about this..

v1 is defined later in the code, not in the beginning with other vectors.
There is a comment about it:
//The size of v1 depends on the image size and must be declared here
There is line 238, where v04.push_back(A1D_ELEM(v1,n)); in for loop, which
goes from n = 0 and I believe that this first value is problematic. The
other values, including those you printed, are all ok.

Ok, I see that this descriptor is related with the autocorrelation peak. 0
index is the energy of the image (I think). So it is strange that you get
the same value for all your particles... Could be a bug in
auto_correlation_matrix...

Best regards
Javier

**Comment by majtner** [comment]
> Ok, now I see.. you are right. I do not have the code fresh but I think that should be a reason for excluding 0... not sure about this.. 

I was also thinking that 0 maybe should be excluded but there is reserved space for it:
v04.reserve(numDescriptors0+numDescriptors1+numDescriptors2+numDescriptors3+numDescriptors4); where numDescriptors0 is 3 but only two values are later added in loop

**Comment by 1aviervargas** [comment]
yes, agree with you...It is likely to be a bug...

Thanks
Javier

**Comment by majtner** [comment]
Only partially solved. I added line 211 to image_sort_by_statistics.cpp: 
v04.push_back(A1D_ELEM(v0,0)); 
so A1D_ELEM(v0,0) is added to feature vector.

However, not sure why A1D_ELEM(v1,n) is always constant (or at least was in my tests), I did not test it further since reporting here.
