### ISSUE TITLE
hide Section Tab(form) if all options are advanced

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1558]
Now, it is impossible hide a section even if  expertLevel is set to LEVEL_ADVANCED.

**Comment by pconesa** [comment]
Aha! You are alive! ;-)... and giving work already!

**Comment by pconesa** [comment]
@delarosatrevin , turns out that the section widget is not a widget like the others. To implement de condition I will require some refactoring, I personally think is not worth it now (unless I'm not seeing the easy way). ;-) 

My suggestion would be to, as you suggested, take into account also the conditions of the widgets that are contained, not only the expert level, but not allow the definition of a condition for the section.

Opinions?

**Comment by pconesa** [comment]
wait! I might have seen the light!...:-)
