### ISSUE TITLE
Issues with RELION in scipion

### ISSUE THREAD

**Issue by krochon** [I2PC/scipion#1598]
Hello,

I've had some challenges getting RELION to work for me in Scipion. I am working with my own data. I ran a gauto particle pick in Scipion, extracted the particles, and then ran a RELION 2D classification. It seemed to work but when I look at the classes, the output is a red "X" for the images. I did find this thread https://github.com/I2PC/scipion/issues/1430, but it seems the issue was closed without resolution to the problem. Is there a recommended solution? 

I have not gotten RELION to behave very well in general and I wonder if I have some configuration incorrect? For example, the only way I can get the job to run 4 threads on each GPU (16 threads total) is to use only one MPI and 16 threads. In the RELION gui I run 5 mpi with 4 threads so that one core is handling each GPU. 

Any insight would be helpful, I like the idea of a single project tree or organization, but RELION is my preferred platform for this project. 

Kristy

**Comment by pconesa** [comment]
Hi @krochon how did you installed:
scipion: Binaries sources?
relion, through scipion or it was already installed or you installed separately.

**Comment by krochon** [comment]
Hi @pconesa, thanks for the reply. I already had many of the programs installed on the system and am using symbolic links for these programs.

**Comment by pconesa** [comment]
In that case....it might be an MPI version compatibility? are scipion MPI paths the same as those used to compile relion?

**Comment by krochon** [comment]
This is a good question, I do not have a symbolic link to mpi in the scipion folder. We're currently using mpich, will that work or is openmpi preferred? 

If mpich is ok, can I just call the bin directory, or should I specify a target in bin?

**Comment by pconesa** [comment]
Well, in theory any mpi framework should work. This is not my experience but never heard of mpich.
Try this, tell scipion that you want to use mpich:
1.- edit <SCIPION_HOME>/config/scipion.conf
2.- In the MPI variables point to your mpich

The problem with this is that now you can only have one MPI in scipion. This means that RELION and XMIPP and others MPI dependant software must share it.

**Comment by krochon** [comment]
Ok, so I checked my config and checked the path for the MPI. I realized we do have openMPI on the system and this is where the config file is pointing; however, it is in a different directory than the directory used to compile RELION.

I tested the config edits to point to mpich and reran the RELION 2d classification. It seems to be sorting the particles, but has no file to render for the display view. This run, it still would not allow me to run the job with more than 1 MPI. For background if it helps, this is a 4-GPU system with one processor containing 12 cores.

![screenshot from 2018-05-11 12-00-05](https://user-images.githubusercontent.com/39163320/39934158-f6230f62-5512-11e8-984b-458e8dc2f2bf.png)

**Comment by phongnq94** [comment]
Hello,
I also have a problem with Relion on Scipion when I ran relion 2D classification. 
On the output log it appreared like this:
´´CalledProcessError: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001561_ProtRelionClassify2D/extra/relion --i Runs/001561_ProtRelionClassify2D/input_particles.star --particle_diameter 340 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00076:   Protocol failed: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001561_ProtRelionClassify2D/extra/relion --i Runs/001561_ProtRelionClassify2D/input_particles.star --particle_diameter 340 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1 ´´

On the other hand, when I ran that data by xmipp3 - cl2d it worked fine. I just want to know why I have that problem and how to fix that? I also want to transfer data and run on relion GUI seperatly but I cannot find the star file to run on relion GUI.

**Comment by azazellochg** [comment]
Hi @phongnq94 , could you post the content of run.stdout? It's usually more informative than the run.log.

**Comment by phongnq94** [comment]
> Hi @phongnq94 , could you post the content of run.stdout? It's usually more informative than the run.log.

The information I have posted is on run.stdout of the Output Log on the Scipion GUI.
Here are the full content on run.stdout

"
00001:   RUNNING PROTOCOL -----------------
00002:         Scipion: v1.0.0
00003:      currentDir: /home/phong/ScipionUserData/projects/Pol3IN1_glu_SECB1_NS
00004:      workingDir: Runs/001403_ProtRelionClassify2D
00005:         runMode: Continue
00006:             MPI: 3
00007:         threads: 1
00008:   len(steps) 3 len(prevSteps) 0
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: convertInputStep, step 1
00012:     2019-02-06 16:18:34.827621
00013:   Converting set from 'Runs/001349_XmippProtCropResizeParticles/particles.sqlite' into 'Runs/001403_ProtRelionClassify2D/input_particles.star'
00014:   FINISHED: convertInputStep, step 1
00015:     2019-02-06 16:18:37.490284
00016:   STARTED: runRelionStep, step 2
00017:     2019-02-06 16:18:37.642901
00018:   mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 3 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1
00019:    === RELION MPI setup ===
00020:    + Number of MPI processes             = 1
00021:    + Master  (0) runs on host            = ubuntu
00022:    =================
00023:    === RELION MPI setup ===
00024:    + Number of MPI processes             = 1
00025:    + Master  (0) runs on host            = ubuntu
00026:    =================
00027:    === RELION MPI setup ===
00028:    + Number of MPI processes             = 1
00029:    + Master  (0) runs on host            = ubuntu
00030:    =================
00031:    Running CPU instructions in double precision. 
00032:   The following warnings were encountered upon command-line parsing: 
00033:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00034:    Running CPU instructions in double precision. 
00035:   The following warnings were encountered upon command-line parsing: 
00036:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00037:    Running CPU instructions in double precision. 
00038:   The following warnings were encountered upon command-line parsing: 
00039:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00040:   ERROR: 
00041:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00042:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00043:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00044:   ERROR: 
00045:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00046:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00047:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00048:   ERROR: 
00049:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00050:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00051:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00052:   --------------------------------------------------------------------------
00053:   mpirun noticed that the job aborted, but has no info as to the process
00054:   that caused that situation.
00055:   --------------------------------------------------------------------------
00056:   Traceback (most recent call last):
00057:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00058:       self._run()
00059:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00060:       resultFiles = self._runFunc()
00061:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00062:       return self._func(*self._args)
00063:     File "/home/eva/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 600, in runRelionStep
00064:       self.runJob(self._getProgram(), params)
00065:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00066:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00067:     File "/home/eva/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00068:       env=env, cwd=cwd)
00069:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 51, in runJob
00070:       return runCommand(command, env, cwd)
00071:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00072:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00073:     File "/home/eva/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00074:       raise CalledProcessError(retcode, cmd)
00075:   CalledProcessError: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 3 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00076:   Protocol failed: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 3 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00077:   FAILED: runRelionStep, step 2
00078:     2019-02-06 16:18:39.047373
00079:   Cleaning temporarly files....
00080:   ------------------- PROTOCOL FAILED (DONE 2/3)
00081:   RUNNING PROTOCOL -----------------
00082:         Scipion: v1.0.0
00083:      currentDir: /home/phong/ScipionUserData/projects/Pol3IN1_glu_SECB1_NS
00084:      workingDir: Runs/001403_ProtRelionClassify2D
00085:         runMode: Continue
00086:             MPI: 3
00087:         threads: 1
00088:   len(steps) 3 len(prevSteps) 3
00089:    Starting at step: 2
00090:    Running steps 
00091:   STARTED: runRelionStep, step 2
00092:     2019-02-06 16:20:01.945334
00093:   mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1
00094:    === RELION MPI setup ===
00095:    + Number of MPI processes             = 1
00096:    + Master  (0) runs on host            = ubuntu
00097:    =================
00098:    === RELION MPI setup ===
00099:    + Number of MPI processes             = 1
00100:    + Master  (0) runs on host            = ubuntu
00101:    =================
00102:    === RELION MPI setup ===
00103:    + Number of MPI processes             = 1
00104:    + Master  (0) runs on host            = ubuntu
00105:    =================
00106:    Running CPU instructions in double precision. 
00107:   The following warnings were encountered upon command-line parsing: 
00108:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00109:    Running CPU instructions in double precision. 
00110:   The following warnings were encountered upon command-line parsing: 
00111:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00112:    Running CPU instructions in double precision. 
00113:   The following warnings were encountered upon command-line parsing: 
00114:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00115:   ERROR: 
00116:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00117:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00118:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00119:   ERROR: 
00120:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00121:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00122:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00123:   ERROR: 
00124:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00125:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00126:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00127:   --------------------------------------------------------------------------
00128:   mpirun noticed that the job aborted, but has no info as to the process
00129:   that caused that situation.
00130:   --------------------------------------------------------------------------
00131:   Traceback (most recent call last):
00132:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00133:       self._run()
00134:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00135:       resultFiles = self._runFunc()
00136:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00137:       return self._func(*self._args)
00138:     File "/home/eva/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 600, in runRelionStep
00139:       self.runJob(self._getProgram(), params)
00140:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00141:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00142:     File "/home/eva/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00143:       env=env, cwd=cwd)
00144:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 51, in runJob
00145:       return runCommand(command, env, cwd)
00146:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00147:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00148:     File "/home/eva/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00149:       raise CalledProcessError(retcode, cmd)
00150:   CalledProcessError: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00151:   Protocol failed: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00152:   FAILED: runRelionStep, step 2
00153:     2019-02-06 16:20:03.317721
00154:   Cleaning temporarly files....
00155:   ------------------- PROTOCOL FAILED (DONE 2/3)
00156:   RUNNING PROTOCOL -----------------
00157:         Scipion: v1.0.0
00158:      currentDir: /home/phong/ScipionUserData/projects/Pol3IN1_glu_SECB1_NS
00159:      workingDir: Runs/001403_ProtRelionClassify2D
00160:         runMode: Continue
00161:             MPI: 3
00162:         threads: 1
00163:   len(steps) 3 len(prevSteps) 3
00164:    Starting at step: 2
00165:    Running steps 
00166:   STARTED: runRelionStep, step 2
00167:     2019-02-06 16:22:20.657700
00168:   mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1
00169:    === RELION MPI setup ===
00170:    + Number of MPI processes             =  === RELION MPI setup ===
00171:    + Number of MPI processes             = 1
00172:    + Master  (0) runs on host            = ubuntu1
00173:    + Master  (0) runs on host            = ubuntu
00174:   
00175:    =================
00176:    =================
00177:    === RELION MPI setup ===
00178:    + Number of MPI processes             = 1
00179:    + Master  (0) runs on host            = ubuntu
00180:    =================
00181:    Running CPU instructions in double precision. 
00182:   The following warnings were encountered upon command-line parsing: 
00183:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00184:   The following warnings were encountered upon command-line parsing: 
00185:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00186:    Running CPU instructions in double precision. 
00187:   The following warnings were encountered upon command-line parsing: 
00188:   WARNING: Option --memory_per_thread	is not a valid RELION argument
00189:    Running CPU instructions in double precision. 
00190:   ERROR: 
00191:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00192:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00193:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00194:   ERROR: 
00195:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00196:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00197:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00198:   ERROR: 
00199:   MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
00200:   File: /usr/local/relion-2.0-source/src/ml_optimiser_mpi.cpp line: 565
00201:   application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
00202:   --------------------------------------------------------------------------
00203:   mpirun noticed that the job aborted, but has no info as to the process
00204:   that caused that situation.
00205:   --------------------------------------------------------------------------
00206:   Traceback (most recent call last):
00207:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00208:       self._run()
00209:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00210:       resultFiles = self._runFunc()
00211:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00212:       return self._func(*self._args)
00213:     File "/home/eva/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 600, in runRelionStep
00214:       self.runJob(self._getProgram(), params)
00215:     File "/home/eva/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00216:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00217:     File "/home/eva/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00218:       env=env, cwd=cwd)
00219:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 51, in runJob
00220:       return runCommand(command, env, cwd)
00221:     File "/home/eva/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00222:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00223:     File "/home/eva/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00224:       raise CalledProcessError(retcode, cmd)
00225:   CalledProcessError: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00226:   Protocol failed: Command 'mpirun -np 3 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 25 --norm  --memory_per_thread 2 --ctf  --offset_range 5.0 --oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter 312 --K 16 --psi_step 10.0 --ctf_phase_flipped  --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 14.2  --j 1' returned non-zero exit status 1
00227:   FAILED: runRelionStep, step 2
00228:     2019-02-06 16:22:22.053165
00229:   Cleaning temporarly files....
00230:   ------------------- PROTOCOL FAILED (DONE 2/3)
"

**Comment by delarosatrevin** [comment]
Hi, I think there is some problem with your MPI configuration in Scipion.
Can you take a look (or share) the hosts.conf (under scipion/config folder)?

From the log I see that Relion is complaining about just one single MPI
node (three times). This issue comes from the following command line:
mpirun -np 3 -bynode which relion_refine_mpi --tau2_fudge 2 --scale --iter
25 --norm --memory_per_thread 2 --ctf --offset_range 5.0 --oversampling 1
--o Runs/001403_ProtRelionClassify2D/extra/relion --i
Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter
312 --K 3 --psi_step 10.0 --ctf_phase_flipped --flatten_solvent --zero_mask
--offset_step 2.0 --angpix 14.2 --j 1

This is just running the which command with mpi and not the relion argument.
It should be something like this:

mpirun -np 3 -bynode `which relion_refine_mpi` --tau2_fudge 2 --scale
--iter 25 --norm --memory_per_thread 2 --ctf --offset_range 5.0
--oversampling 1 --o Runs/001403_ProtRelionClassify2D/extra/relion --i
Runs/001403_ProtRelionClassify2D/input_particles.star --particle_diameter
312 --K 3 --psi_step 10.0 --ctf_phase_flipped --flatten_solvent --zero_mask
--offset_step 2.0 --angpix 14.2 --j 1

The difference is in `which relion_refine_mpi` that should output the full
path to the command and then, this is what is taken by mpirun.

Hope this help to fix this issue,
Best,
Jose Miguel

**Comment by phongnq94** [comment]
Thank you @delarosatrevin . When I change the MPI value it seems to work fine.

**Comment by azazellochg** [comment]
@krochon was this solved?
