### ISSUE TITLE
devel compile fails at ctf_estimate_from_psd

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1614]
I have the same error on my PC (gcc 6.3.0 20170516) and laptop (gcc 7) during devel compilation:
```
software/em/xmipp/libraries/reconstruction/ctf_estimate_from_psd_base.h:110:32: error: 'constexpr' needed for in-class initialization of static data member 'const double ProgCTFBasicParams::penalty' of non-integral type [-fpermissive]
  static const double penalty = 32; // Maximum penalization
                                ^~

```
As soon as I replace const with constexpr it compiles.

**Comment by delarosatrevin** [comment]
I think constexp was introduced in C++11 (gcc support from 4.8). So, I will suggest to do the initialization out of the class, i.e, in the .cpp file.

**Comment by dmaluenda** [comment]
I have found the same problem installing scipion in Ubuntu18.04. With Coss, we have consider to update the code (i.e. I will commit a new version of ctf_estimation_from_psd_base.h with constexpr).

Then, in order to keep the back compatibility, we add -std=c++11 in config templete.

I commited this in devel-fixes branch [62c8a0613c5835f72aa593fee82fcc01a8465863]

**Comment by delarosatrevin** [comment]
I really like all the new stuff introduced in c++ 11, but I'm not sure if make sense only for using 'constexpr' here. But could be a good idea for the future and I guess not many people will be using old compilers these days.

**Comment by dmaluenda** [comment]
It just has been the excuse to update. It's done

**Comment by delarosatrevin** [comment]
Great! But is should be clearly stated in the installation instructions.

**Comment by azazellochg** [comment]
I guess this can be closed.
