### ISSUE TITLE
help button not displayed in GUI form when there are two params in Line

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1732]
Also, besides Help button missing, the whole form is distorted :)

![screenshot_20180818_223532](https://user-images.githubusercontent.com/6952870/44303368-25f2d480-a337-11e8-809c-8b10f14a5375.png)

**Comment by pconesa** [comment]
I'm having a look at this one.

**Comment by pconesa** [comment]
I've spent some time understanding, aligning and tweaking this form. Just now I looked specifically to this issue. Turns out that is intentionally done: 'showButtons=False'
Here: https://github.com/I2PC/scipion/blob/devel/pyworkflow/gui/form.py#L1938

@delarosatrevin, any reason to stop here or should we try to display buttons too.
