### ISSUE TITLE
opening a "devel" project with 1.2.1 fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1767]
**Describe the bug**
A project opened with devel can't be opened with release-1.2.1 and probably any previous version.

**To Reproduce**
1. Open a project with "devel" as of today and close it.
2. Open it with release-1.2.1
3. It does not open.

**Comment by pconesa** [comment]
At least do not fail if the icon reffered in settings.sqlite.....is not valid or not present.

**Comment by dmaluenda** [comment]
Could it be related with the icon filename in the settings.sqlite issue??

**Comment by delarosatrevin** [comment]
What is the error? related to something in settings.sqlite?

**Comment by pconesa** [comment]
Yes is the icon issue...we have changed the icon in devel to work in ubuntu 18 too. The icon is saved in settings.sqlite. and when trying to open  a new project , that has, in the settings.sqlite and icon that does not exist....it fails.
My idea is to, tolerate the absence of the icon for 1.2.1....and for devel do not save the icon...@delarosatrevin.....any good reason to keep the icon in the settings.sqlite?

**Comment by delarosatrevin** [comment]
I can't remember exactly why it was stored there. It is stored because we thought in the possibility of scipion being used as library/framework and to allow to define other icons to be used in the GUI. Anyway, probably is better to have such a thing in a .conf text file or similar. Maybe beyond this issue, could be good to review/check other things that are stored in settings.sqlite.

**Comment by pconesa** [comment]
Ok, I'll do something now to prevent this issue in release-1.2.1
