### ISSUE TITLE
Monores results are not aligned

### ISSUE THREAD

**Issue by clee02** [I2PC/scipion#1800]
Hi,
I tried to import half maps from cryosparc or relion (not internally from scipion) for Monores.
When I checked the MG_Chimera_reolution.vol, I found it is not aligned with the input maps.
So I am not sure if monores run properly. Did I do something wrong? 

Thank you.

**Comment by clee02** [comment]
Just an update, if I used resmap, the result is also not aligned with the input maps. Maybe there are some shifts happened to the maps during Importing?

Thanks.

**Comment by Vilax** [comment]
Hi clee02,

You did it everything right. And your resolution map should be good.

We have noticed this problem. It is a shift between the electron density map and the local resolution map. In our experience it hardly ever happens, but despite that your resolution map should be good, it is only visualization problem.

The solution is carried out in chimera, as it follows

In the volume viewer window -> features-> coordinates
The window will show more parameters. You have to change the  Origin index. Probably the value is non equal zero, doing this it should be fixed. Otherwise you have to determine the shift.

I it did not work please let it me know

Regards

Vilas

**Comment by delarosatrevin** [comment]
Have you checked if the correct pixel size is set in Chimera?

I think the visual wrong shift happened here as well when visualizing a
volumen...and not related to local resolution.

**Comment by pconesa** [comment]
@clee02 , are you able to paste a screenshot of the problem?

**Comment by josuegbl** [comment]
I guess this problem is related with the formats of the maps. Ussualy, the halves maps (and also the final refined map) are mrc, but the resolution map obtained by monores is .vol (in other words, .spi). As far as I know, spi volumes not store in the header both pixel size and center, but mrc format does.

**Comment by clee02** [comment]
I thank everybody for their input. Indeed, the problem is .vol format. In Chimera, for both maps the Origin indexes are the same for the two maps (both zero), but the voxel size of .vol is wrong. After I changed that, the two maps are aligned.

**Comment by pconesa** [comment]
Can this be closed, or is there anything we can do to prevent this from happening? @josuegbl

**Comment by josuegbl** [comment]
I think the best solution is save the resolution map in mrc format, with the same header as original map. THis is a xmipp thing, so I think you can close it here
