### ISSUE TITLE
untar command is never executed when createBuildDir =True

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1803]
**Describe the bug**
untar command is never executed when createBuildDir =True

**To Reproduce**
1. I have the following
```      
spider_commands = [
            ('mv ../spider ../web  .',  # we are in spider-24.03 dir already
             '%s/spider-24.03/spider/bin/spider' % SW_EM)]

env.addPackage('spider', version='24.03',
                       url='https://spider.wadsworth.org/spider_doc/spider/download/spiderweb.24.03.tar.gz',
                       createBuildDir=True,
                       commands=spider_commands,
                       neededProgs=['csh'],
                       default=True)
```
2. Run `scipion installb spider`
3. Since createBuildDir=True, it does execute mkdir, but then tar command is skipped since the target dir (just created, but empty!) already exists!

```
mkdir /home/azazello/soft/scipion-devel/software/em/spider-24.03
  Skipping command: tar -xzf spider-24.03.tgz -C spider-24.03
  All targets exist.
```

**Expected behavior**
Maybe this code in install/funcs.py should be changed to check if target is a non-empty dir
```
    def _existsAll(self):
        """ Return True if all targets exist. """
        for t in self._targets:
            if not glob(t):
                return False
        return True
```

**Desktop (please complete the following information):**
 - devel-pluginization branch

**Comment by yaizar** [comment]
I'm a bit against adding that check to _existsAll, because that would imply returning False even if the target exists. The following works:
```env.addPackage('spider', version='24.03',
                       url='https://spider.wadsworth.org/spider_doc/spider/download/spiderweb.24.03.tar.gz',
                       createBuildDir=True,
                       buildDir='spider', 
                       target="spider/spider",  
                       neededProgs=['csh'],
                       default=True)
```
We must use buildDir to specify how we wanna name the directory where we will untar things. We can't use the default name (spider-24.03) because Scipion will fail to create the link with that name (maybe we should reconsider this behavior? if name-version already exists then don't make a link?) Anyway it seems ok with me that you have to provide a buildDir name if createBuildDir=True.
Then we must use target to specify the FINAL target. I think this is necessary anyway because if we have to create a builddir (even if we adapt the link thing and we create name-version by default), it is impossible for scipion to know what needs to be inside the build dir to consider the extraction successful. What we can do is tell scipion that the final target will be join(buildDir, target) if buildDir was specified so we avoid repeating it in the target. thoughts? @pconesa?

**Comment by pconesa** [comment]
ufff! I would need to understand all a bit more. My concern now is not to break the installation of other stuff with this change.

**Comment by pconesa** [comment]
After @yaizar explanation I 'd stay on the safe side and use her suggestion. Mainly bacause it does not require code changes in the Environ class.
