### ISSUE TITLE
defineVar in Plugin class not working properly?

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1814]
**Describe the bug**
defineVar adds Scipion path to var, while defineEmVar works correctly by adding EM_ROOT to the var.

**To Reproduce**
1. Set GCTF = some binary in scipion.conf and GCTF_HOME to some home
2. Protocol will fail, because binary was not defined correctly. You can see it by doing `scipion printenv | grep GCTF`:
```
export GCTF="/home/azazello/soft/scipion-devel/Gctf-v1.18_sm_30_cu8.0_x86_64"
```

**Expected behavior**
defineVar in plugin class should not add scipion path to the var. 

**Desktop (please complete the following information):**
 - devel-pluginizarion branch

I could not find why this happens. A lot of plugins (but not all!!) use os.path.basename(GCTF) to get only the basename.

**Comment by yaizar** [comment]
what you put in scipion.conf is only Gtctf-v1.18_sm_30_cu8.0_x86_64 but the value in Scipion is that whole path?

**Comment by yaizar** [comment]
defineVar doesn't add anything to the path:
https://github.com/I2PC/scipion/blob/devel-pluginization/pyworkflow/plugin.py#L186

If you want to define the location of the binary in scipion.conf, you should use an absolute path, otherwise scipion will prepend scipion's location. Closing this.

**Comment by azazellochg** [comment]
@yaizar thanks, I didnt know about adding scipion root to everything. Means I have to fix a few plugins..

**Comment by yaizar** [comment]
to everything in scipion.conf!!! The things you defined in your plugins should be unaffected by this I think, because they don't end up in this file, but you'll know better

**Comment by delarosatrevin** [comment]
Wait, wait. I think this is a good moment to review certain behaviours. I think we should not add scipion root (or EM_ROOT) to everything in scipion.conf, maybe only some of them. Maybe this is a point we should discuss during the developers meeting.

**Comment by yaizar** [comment]
I think if you put a relative path in scipion.conf it is very safe to
assume it is inside the SCIPION_HOME. Where else would you look for it?

**Comment by delarosatrevin** [comment]
Before it made sense, when all plugins (and code) were inside the Scipion folder. But now each plugin is a standard Python package (and would be good to have Scipion as a package as well). So, if we think that scipion.conf is a good place to put default values for environment variables (not even necessarily only restricted to path variables), then it does not make sense anymore to prepend the SCIPION_HOME value to that. 

I think this bite me in the past when trying to define a non-path variable...and then I should use the dirty fix of using basename later to retrieve the value. :(

**Comment by azazellochg** [comment]
Guys, the problem is not the plugin path but the binary name. I don't
understand why you want to append scipion root to it.
The original problem for me was that when I concatenate plugin home and
plugin  binary I get wrong path, which looked like
plugin-home/scipion-home/binary

**Comment by yaizar** [comment]
@delarosatrevin maybe it doesn't make sense to prepend SCIPION_HOME variable - agree on that, but I think it also doens'tn make sense to host general plugin variables in scipion.conf (If there are any, put them in the environment and launch scipion in that environment? Instead of doing dirty fixes). Also, right now scipion.conf is not meant for default plugin values at all. Defaults should ALWAYS be defined in the plugin and the plugin should be able to run **without putting anything in scipion.conf**. We are supporting putting there the binary paths because it is a case generic enough for all plugins, so if the user wants to **personalize** the binary used, she/he can add it there. 
So the behavior as it is right now is:
- check if SOME_HOME is in the environment, and use it AS IT IS if present (no path concatenating @azazellochg, since this is meant for personalization, I don't think the plugin should be messing with this). 
- Use plugin's default for SOME_HOME if not present (defaults are defined with defineEmVar or defineVar, and these work as you expect I think).

**Comment by yaizar** [comment]
Also, I just checked, if the variable is defined in the [VARIABLES] section it is left alone:
`scipion printenv`
![image](https://user-images.githubusercontent.com/4609687/47648436-4f6f7e00-db7a-11e8-9500-f2d32644883d.png)

So any vars there won't have SCIPION_HOME prepended. Anyways I think it would be good if paths defined there are absolute, but obviously that'll be up to the plugin developer how to deal with their vars.

**Comment by azazellochg** [comment]
I am talking about personalisation as well. Everything works fine if plugin takes care of default var (for both software home and binary), but it does not work if I try to personalise it and put my own binary there. Basically, the old scipion-1.x way:
GCTF_HOME = %(EM_ROOT)s/gctf-1.18
GCTF = Gctf_v1.18_b2_sm62_cu9.1

is not working unless I do the following:

GCTF_HOME = %(EM_ROOT)s/gctf-1.18
GCTF = %(EM_ROOT)s/gctf-1.18/bin/Gctf_v1.18_b2_sm62_cu9.1

Anyway, the problem is now solved by taking basename of any GCTF variable, whether it was defined in plugin (default) or by scipion.conf.

**Comment by yaizar** [comment]
OK! Well if that's not acceptable you can put it under [VARIABLES].

**Comment by delarosatrevin** [comment]
@yaizar I think it still make sense to use scipion.conf as a replacement for the environment setup. I think more flexibility is better, since in the environment probably it will be used for many scipion installation or will also depends in the bash your are using for defining variables. So, I still think that we should discuss about the use of scipion.conf and if it will be convenient to put variables (path or not) for plugins there, as an alternative way of the environment or the central installation. In that way we could give users the possibility of some customization if needed.

**Comment by delarosatrevin** [comment]
Yes, in the example @azazellochg mentioned of GCTF, the GCTF_HOME make sense to use the path, but not the GCTF, that is a binary and specifying the whole path is redundant and more difficult to update.

**Comment by yaizar** [comment]
Sure. Is the variables section an OK place to put them?

**Comment by delarosatrevin** [comment]
I will say that it more natural to place all variables related to a plugin (in case we decide to allow plugin vars in scipion.conf) together, either in [PACKAGES] or [VARIABLES], or maybe we should define sections per-plugins...but have variables in different place will be more annoying.

**Comment by pconesa** [comment]
I agree we should not add by default SCIPION_HOME to the variables. Which is been like this if I'm right.
We should be 100% flexible and allow any value and facilitating prefixing any variable with some "SCIPION VARS" like SCIPION_HOME, SCIPION_EM,.....but just a binary or a boolean should be specified.
