### ISSUE TITLE
hot reload of plugin after plugin update

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1954]
When there is an update of a plugin, the update does not do a "hot reload" of the new plugin, the main consequence is that the binary associated is not triggered and therefore not installed.

This is a bit tricky, and at this point we can:
a.- Ideally fix it
b.- Pop up a message to the user to restart scipion and manually install the possible new binaries (e.g updating relion plugin to new version that offers relion 3)
c.- maybe launching the plugin manager isolated?

The reason is that all the classes (protocols, viewers, wizards, objects) of the plugins are loaded and unload them seems to be very complicated. Yet we are trying to make it work.

**Comment by delarosatrevin** [comment]
Hi @pconesa , 

I don't fully understand the case here and what you mean by "hot reload". 

Let's see if you got the case:
1) User/admin update one plugin. 
What is the "hot reload" that is missing? After updating a plugin, I see two cases (related to this)
a) There are new binaries associated with the plugin, some questions then...should the binary be installed automatically? Should the it configure as new default? I think there is not easy answer and pros/cons
b) Only plugin updates..no new binary, so there is not much deal in this one.

In any case, I still don't get what "hot reload" means...because if you have the GUI open, I think it is reasonable that the user close/open it after an update.

**Comment by delarosatrevin** [comment]
One more thing...is this so critical that will be addressed for v2.0 (that is supposed to be frozen)?

**Comment by dmaluenda** [comment]
I don't know if I fully understand the issue, but in the case that Scipion needs to be re-starded, I will vote for @pconesa's option c (launch plugin manager in an isolated way).

Additionally, regarding the @delarosatrevin questions, I vote for don't automatically install binaries in any case (new plugin installation neither update), maybe just marking the default binary/ies as 'to install' it's enough.

**Comment by pconesa** [comment]
You are getting it right, with hot update, I mean to refresh the "plugin" with the updated version, without the need of exiting the plugin manager.

Good news is that @fonsecareyna82 manage to do it right now.

Now, regarding the behaviour, installing or not by default the binaries upon update/install....

I can see both options useful:

A.- Installing the plugin will install de default binaries
B.- Binaries must be installed manually by the user.

In any case (even B) the "hot load" is useful to reflect that new binaries are available without exiting Scipion.

Obviously, the plugin developer can define no binaries as default, and maybe we could have an option in the plugin manager to let the user decide what to do with the binaries?

**Comment by delarosatrevin** [comment]
Yes, the "refresh" make sense in the Plugin manager, but I was confused about the need in the others GUIs, where I think it is reasonable to close and open if one has installed one update.
