### ISSUE TITLE
Undefined symbol in libXmipp.so

### ISSUE THREAD

**Issue by runiq** [I2PC/scipion#1997]
**Describe the bug**
I'm trying to run the `pyworkflow.tests.em.data.test_data` test, but it's failing with:

```

Scipion v2.0 (2019-04-23) Diocletian

>>>>> python  /home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/apps/pw_run_tests.py "pyworkflow.tests.em.data.test_data"

Xmipp installation have failed or xmipp's C++ binnding have some problem:
/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/software/em/xmipp/lib/libXmipp.so: undefined symbol: _ZNK2H56H5File14throwExceptionERKSsS2_

  > Please, remove the Xmipp installation (usually 'rm software/em/xmipp') and re-install it

Traceback (most recent call last):
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/apps/pw_run_tests.py", line 45, in <module>
    import pyworkflow.tests as pwtests
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/tests/__init__.py", line 29, in <module>
    from tests import *
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/tests/tests.py", line 11, in <module>
    from pyworkflow.project import Manager
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/project/__init__.py", line 28, in <module>
    from .project import Project, MissingProjectDbException
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/project/project.py", line 37, in <module>
    import pyworkflow.em as em
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/em/__init__.py", line 31, in <module>
    from data import *
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/em/data.py", line 36, in <module>
    from convert import ImageHandler
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/em/convert/__init__.py", line 28, in <module>
    from .image_handler import ImageHandler, DT_FLOAT
  File "/home/software/+gcc-7.2/+openmpi-2.1/scipion/2.0.0/pyworkflow/em/convert/image_handler.py", line 38, in <module>
    sys.exit(-1)
NameError: name 'sys' is not defined
```

**To Reproduce**

1. Install GCC 7.2.0
1. Install Scipion using GCC 7.2.0
1. `scipion installp -p scipion-em-xmipp`
1. `scipion installb xmippBin_Centos`
1. `scipion test pyworkflow.tests.em.data.test_data`

**Expected behavior**

The test should actually start.

**Desktop (please complete the following information):**

- OS: CentOS 7.6.1810 x86_64
- Scipion compiled using GCC 7.2.0

**Additional context**

That might be an error with different compiler versions: I'm trying to run Scipion on an HPC cluster, and I'm using a newer GCC version (7.2.0) than the one that comes with the distro (4.8.5 on CentOS 7). Maybe they changed their symbol packing scheme in the meantime.

I tried to use the `xmippSrc` bin target instead, but it has a rat's tail of dependencies, so I wanted to try and get the bin target to work.

**Comment by dmaluenda** [comment]
Hi @runiq,

Usually this error is gotten when xmippBin_Centos is used in Ubuntu distros or the oposite. Even though you are using in the right way Centos binary in Centos distro, I would try to use the xmippBin_Debian and see if it's fixed, since Ubuntu18 comes with that compiler (I think).

Remember to delete `software/em/xmipp` link before launching Scipion to re-install xmipp. If not, you will get this error before you can do anything.

Regading the large number of dependencies, many of them are usually in the system by default. We put all them in order to make sure that they will be there. Therefore, you can try to install Xmipp from source (then, you need Scipion from sources too) in a single node and see which library is missing to install it. The drawback here is that you should repeat this for each missing library (try/error procesure) and, moreover, you need to export that installations to the other nodes...

Thanks for reporting!

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.

**Comment by pconesa** [comment]
New release of Scipion 3.0 changes all installation environment and xmipp will change too.
