### ISSUE TITLE
Allow downsample when extracting particles even if using same micrographs

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#313]
The downsampling parameters make sense even if using the same set of micrograph to extract the particles.

**Comment by azazellochg** [comment]
The same applies to extract tilt pair particles, right now there is no way to downsample them (even in resize/crop protocol)

**Comment by azazellochg** [comment]
@delarosatrevin Right now if downsampleType == OTHER then user has to provide a downFactor that will be used to dowmsample OTHER mics (!) before extraction. 

Don't you think it would be more reasonable to: 
a) calculate downfactor automatically from sampling rates of "picked" mics (can be related from inputCoords) and OTHER mics;
b) recalculate coordinates before extraction rather than downsample micrographs?

**Comment by delarosatrevin** [comment]
This issue is addressed in #566
