### ISSUE TITLE
Bug of Detector pixel size in Relion star files

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#323]
Reported by @azazellochg

I have noticed that in scipion-produced relion star files (after 2d classification relion protocol) the_rlnMagnification column is wrong (it prints nominal 59000 instead of actual 31818) and there is no _rlnDetectorPixelSize column in output star files. 

That's why I wonder what values should be used for Magnification during Micrograph import protocol? 

I have used 59000x and 1.1A/px ("from image") during import. Classification was done on C4 data, hence pixel size 4.4A. Actual mag should be then 4.4/14um=31818 and not 59000 in star file, given our detector size 14um.

**Comment by azazellochg** [comment]
So, the more clear description of the bug is the following: 

1. The detector pixel size column (**_rlnDetectorPixelSize**) is missing in all star files generated by Scipion.
2. **_rlnMagnification** column is correct and it does not change upon coarsing/uncoarsing data - the same behavior as in Relion. We just need to ensure that user provides a correct actual magnification (not the nominal one like 59000 or 50000) when importing micrographs - this can be added to the help message [here](https://github.com/I2PC/scipion/blob/v1.0/pyworkflow/utils/properties.py#L223)
3. Pixel size calculation in Scipion is correct, so e.g. Relion _--angpix_ option has a correct value.

Relion is generally [rechecking](https://github.com/dtegunov/vlion/blob/master/src/ml_optimiser.cpp#L892) star files, looking for both detector pizel size and magnification, calculating pixel size and if it is not the same as _--angpix_ option says, it replaces pixel size with the one calculated from star file.

I have to check Relion behavior in case if only magnification column is present and angpix is indicated (our case in Scipion)..

**Comment by delarosatrevin** [comment]
@azazellochg , I was looking more carefully at the piece of relion code that you sent me and I think this not an issue. Relion only check if you pass both MAGNIFICATION and DETECTOR_PIXEL_SIZE and check that is consistent with --angpix, I think if you only one is passed, the --angpix will be used. 
I will ask in the Relion mailing list to be sure.

**Comment by azazellochg** [comment]
I agree, it is better to ask Sjors.
Okay, but would not it be better to follow Relion rules (add _rlnDetectorPixelSize column) for compatibility, in case someone wants to export files from Scipion and go to Relion?

**Comment by delarosatrevin** [comment]
It seems that we are doing this correctly. Since in Relion you could either pass magnification and detector pixel size OR the --angpix. Since in our case we are not passing the detector pixel size, everything should work as expected. It is not clear to me if there is a preferred way for Relion.
So I will close this issue for the moment.
