### ISSUE TITLE
spider_align_base protocol does not copy CTF metadata to output

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#340]
Whether I run _align ap sr_ or _align pairwise_, the output particle stack has no ctf metadata. I guess **imgSet.copyInfo** is missing [here](https://github.com/I2PC/scipion/blob/v1.0/pyworkflow/em/packages/spider/protocol/protocol_align_base.py#L103).

**Comment by delarosatrevin** [comment]
I think is not the copyInfo...is the inputParticles.copyItems where all input particles information is transferred to the output (of course updating the image filename with the produced stack.

I was in a workshop and I also found that capca is not reading previous alignment (apart from spider where the images are re-written). I added the general issue (#341) about input alignment.

@azazellochg , What do you think to about doing those fixed in the same branch that you already have in a PR related to spider? We could group them together as general spider fixing 'feature'.

**Comment by delarosatrevin** [comment]
@azazellochg Another thing, today in the workshop a person was asking about some other spider AP ??? alignment methods, which one do you think could be helpful to have included?

**Comment by azazellochg** [comment]
@delarosatrevin , I don't mind fixing it in my branch.
About Spider AP commands.. When we were using SPIDER in the lab, the most frequently used things were projection matching with AP SH(C) + AP REF(very fast, very accurate, but very biased) and AP SR for reference-free alignment. Looking [here](http://spider.wadsworth.org/spider_doc/spider/docs/align_overview.html), I don't see anything else worth to implement. AP SA+RA are the same tools as AP SR, just shifts and rotations are separated,  - well this might be useful for advanced users. Also, in general I don't know any other spider protocols that were used often. You might ask this person what else he would like to use.. )

**Comment by delarosatrevin** [comment]
This issue (and also for filter protocols) was fixed here: ac5ddb99bd9da537001b76c328e08828ea314e77
The problem was that copyItems was not used to propagate information from input particles to output.
