### ISSUE TITLE
assignment tilt pair fails if not all mics were picked

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#344]
Dont know whether this is a bug or is it by design..
If in the input MicrographsTiltPair there are mics for which no coordinates exist at all, the protocol fails, looking for pos files that do not exist. I do not know whether user is supposed to pick few tilt pairs for each pair of mics and then run the protocol? 

And btw, how many coordinate pairs are required so that protocol will work? More than 10, so tilt axis should be determined during manual picking? This could be written in tutorial, I think.

**Comment by delarosatrevin** [comment]
@Vilax , can you also check this?

**Comment by Vilax** [comment]
The protocol needs coordinates for working, so if the input micrographs have not been picked, the protocol won´t perform any assignment. This is due to the fact that there isn´t a pos-file to be processed.

According to your request, the protocol has been modified. Currently, if there are some input micrographs which have not been picked or if there’s isn´t any associated pos-file, the protocol will show a warning -instead of an error- and will continue processing all micrographs. This warning informs the user about a particular micrograph that has not been processed.

About the required  number of coordinate pairs:

The algorithm always finds at least three correspondences between tilted and non-tilted particles. The number of assigned tilted pairs is variable. The input of the protocol consists on two independent pickings, one for the untilted micrograph, and the other for the tilted micrograph. They should be possible to be performed manually or automatically, with any picking protocol, XMIPP, EMAN, RELION, .... The tilted pairs assignment protocol tries to find a correspondence between those pickings, but it does not depend on the kind of the picking.
The estimation of the tilt axis is calculated using coordinates (positions). Thus, the more tilted pairs are found, the higher accuracy will be achieved in the determination of the tilt axis. More than 10 tilt pairs could be a reasonably number for determining the tilt axis. Nevertheless, the calculus of the tilt axis depends on the coordinates themselves, not on the number of coordinates. Thus, 10 tilt pairs may be enough in general.

If you have more questions, please do not hesitate to ask.

Thanks

Vilas

**Comment by delarosatrevin** [comment]
@azazellochg , this is fixed now in v1.0 branch...let us know if you can test it again.

**Comment by azazellochg** [comment]
@Vilax thank you for a detailed answer!
Now indeed, a warning message appears if coordinates do not exist, however the protocol fails at the last step:

```bash
00092:   STARTED: createOutputStep, step 8
00093:     2016-03-04 11:54:23.425058
00094:   Traceback (most recent call last):
00095:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00096:       self._run()
00097:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 211, in _run
00098:       resultFiles = self._runFunc()
00099:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 207, in _runFunc
00100:       return self._func(*self._args)
00101:     File "/home/sharov/soft/scipion/pyworkflow/em/packages/xmipp3/protocol_assignment_tilt_pair.py", line 268, in createOutputStep
00102:       outputset.setObjComment(self.getSummary(outputset))
00103:     File "/home/sharov/soft/scipion/pyworkflow/em/packages/xmipp3/protocol_assignment_tilt_pair.py", line 330, in getSummary
00104:       summary.append("Particle size: %d" %self.outputCoordinatesTiltPair.getUntilted().getBoxSize())
00105:   AttributeError: 'XmippProtAssignmentTiltPair' object has no attribute 'outputCoordinatesTiltPair'
00106:   Protocol failed: 'XmippProtAssignmentTiltPair' object has no attribute 'outputCoordinatesTiltPair'
00107:   FAILED: createOutputStep, step 8
```

**Comment by delarosatrevin** [comment]
We have fixed this, @azazellochg , could you test again? and close the issue if everything is fine?

**Comment by azazellochg** [comment]
Now everything works properly!

**Comment by delarosatrevin** [comment]
@azazellochg , Thanks a lot for your help!
