### ISSUE TITLE
short descriptions for small tree

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#386]
The small tree with ids is not useful. Have a short name attribute to be shown in the small tree view

**Comment by delarosatrevin** [comment]
I guess this issue was proposed by @cossorzano , we (me and @josuegbl ) has a discussion about it some days ago. I just want to let here some of the points we talk about:

First, the small tree with ids is useful (although it does not solve other visualization problems), it display a reduced version of the tree....and on hover, it shows more information about the run. 

The short label approach have some drawbacks (from my opinion) and does not solve the problem:
* Requires a new variable to the Protocol class (that developers need to know) just for a visualization stuff
* Short names given by the developers might not be descriptive for the user
* Short names (could be also long depending on the developer) will not provide an unique identifier for each box as the ids approach does.
* Another thing is that right now users have the possibility to annotate their runs with shorter names (given by themselves) that probably are more meaningful.
* Even with the short-names approach, there will be still some big graphs that will need other workaround to improve usability.

**Comment by pconesa** [comment]
Just for clarification. @cossorzano didn't proposed, but I guess the who is not important anyway.

I think if we implement the zoom functionality....then this view will not give you nothing more. 

For the short description: 
it can fall back on the id (so the developer doesn't need to add anything)
I agree that is a visualization thing, so why not storing it with the other visualization data, like the x,y, selected,...attributes.

May be, once other visualization improvements are added, this will not make any more sense.  Although for the zooming option could be a good complement: when the boxes are small then display short name!! ;-).
