### ISSUE TITLE
tilt pair validation protocol

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#515]
I try to use _xmipp3-validate tilt_ protocol, but I don't understand some of its parameters.. 
- "input angles tilt pair" means tilt pair particles I guess..
- Why there is angular sampling and not tilt search range?
- What is significance value? Is there an option to do CTF correction?
- Is there an option to restrict resolution?

**Comment by Vilax** [comment]
Thanks for reporting this issue,

This protocol is still under development, and we are working on it. 
I will leave the issue open in order to remind us that it need to be solved.

Let me explain the parameters:


The protocol use two angular assignments called input angles tilt pair, thus, the angular sampling is the accuracy of the assignment (perhaps this input will be removed), then the tilt angle is calculated.
There is no CTF correction. 

As I tell before, it is under development.

Thanks in advance

Vilas

**Comment by azazellochg** [comment]
Since this protocol doesn't exist anymore,  I close this issue
