### ISSUE TITLE
Python compilation

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#783]
Some people have reported that Python compilation did not work automatically and that they had to compile it manually with

./configure --enable-shared --prefix=/home/apps/src/Scipion/levque/scipion-git-GCC-OpenMPI/software --libdir=/home/apps/src/Scipion/levque/scipion-git-GCC-OpenMPI/software/lib --with-tcltk-includes='-I/home/apps/src/Scipion/levque/scipion-git-GCC-OpenMPI/software/tmp/tk8.6.1/generic/' --with-tcltk-libs='-L/home/apps/src/Scipion/levque/scipion-git-GCC-OpenMPI/software/lib -ltcl8.6 -ltk8.6'

**Comment by azazellochg** [comment]
Python compilation did not work for me:
`Failed to build these modules:
_hashlib              _ssl`
because apparently python 2.7.8 distributed within Scipion is not [patched](https://bugs.python.org/issue26470) to support new openssl >=1.1.0 (they changed API from there on). After few unsuccessful attempts, I replaced 2.7.8 by 2.7.13 which compiled ok.

**Comment by delarosatrevin** [comment]
Thanks a lot @azazellochg , maybe we should consider the possibility to update Python version and some modules and libraries.

**Comment by pconesa** [comment]
This is not needed anymore in scipion3.0
