### ISSUE TITLE
relion - particle extraction

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#983]
relion-particle extraction has not analyze results

**Comment by yaizar** [comment]
Looking into this. The protocol is assigned XmippViewer for visualization because of a parent class (<class 'pyworkflow.em.protocol.protocol_particles.ProtExtractParticles'>), however XmippViewer doesn't check later the parent class and doesn't contemplate visualizing a Relion protocol, so nothing happens. 
Also slightly unrelated and just fyi, I've seen this protocol has an attribute OUTPUT_TYPE=<class 'pyworkflow.em.data.SetOfClasses3D'>  which doesn't make too much sense to me? Looks like it doesn't affect its purpose though.

**Comment by delarosatrevin** [comment]
Hum, if the XmippViewer has ProtExtractParticles as a possible target it should take care of it. I think we need to consider a serious clean-up of XmippViewer at some moment after the release. 

The other issues is weird, it should not have OUTPUT_TYPE, this is a property of the Set classes and should not be stored anyway.
